CREATE TABLE IF NOT EXISTS TBL_CATEGORIAS (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TBL_CATEGORIAS (nome) VALUES ('Lazer');
INSERT INTO TBL_CATEGORIAS (nome) VALUES ('Alimentação');
INSERT INTO TBL_CATEGORIAS (nome) VALUES ('Supermercado');
INSERT INTO TBL_CATEGORIAS (nome) VALUES ('Farmácia');
INSERT INTO TBL_CATEGORIAS (nome) VALUES ('Outros');