CREATE TABLE IF NOT EXISTS TB_CATEGORIAS (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TB_CATEGORIAS (nome) VALUES ('Lazer');
INSERT INTO TB_CATEGORIAS (nome) VALUES ('Alimentação');
INSERT INTO TB_CATEGORIAS (nome) VALUES ('Supermercado');
INSERT INTO TB_CATEGORIAS (nome) VALUES ('Farmácia');
INSERT INTO TB_CATEGORIAS (nome) VALUES ('Outros');